CREATE TABLE IF NOT EXISTS  kul (
	id int(11) NOT NULL auto_increment,
	tc varchar(11) NOT NULL ,
	ad varchar(128) ,
	soyad varchar(128) ,
	kizliksoyad varchar(20) ,
	babaad varchar(30) ,
	anaad varchar(30),
	ceptel varchar(10),
	evtel varchar(10) ,
	email varchar(100) ,
	evadres varchar(100) ,
	il varchar(30) ,
	ilce varchar(30) ,
	uni varchar(100) ,
	bolum varchar(100) ,
	calismakurum varchar(100) ,
	calismabirim varchar(100) ,
	isadres varchar(100) ,
	isil varchar(30) ,
	onkayit varchar(1) ,
	tarih varchar(100) ,
	PRIMARY KEY (id)
) TYPE=MyISAM DEFAULT CHARSET=utf8;
